package br.com.natanaelqn.relatorio.gui;

import br.com.natanaelqn.relatorio.dao.CarroDAO;
import br.com.natanaelqn.relatorio.dao.MotoristaDAO;
import br.com.natanaelqn.relatorio.dao.RelatorioDAO;
import br.com.natanaelqn.relatorio.entity.Carro;
import br.com.natanaelqn.relatorio.entity.Motorista;
import br.com.natanaelqn.relatorio.entity.Relatorio;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class RelatorioGUI extends javax.swing.JFrame {

    public static final DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    public RelatorioGUI() throws ParseException {
        //RelatorioBD.inicializarBD();
        initComponents();
        atualiza();
        popularCombos();
    }
    
    private void atualiza() throws ParseException {
        String[] cposFigurinha = {"Id", "IdMotorista", "IdCarro.", "Data do Serviço", "Data do Envio", "Km Percorrido", "Novas Avarias", "Relato"};
        List<Relatorio> relatorios = RelatorioDAO.selecionarTodos();
        String[][] dadosRelatorios;
        dadosRelatorios = new String[relatorios.size()][8];
        int posicao = 0;
        for (Relatorio relatorio : relatorios) {
            String[] umRelatorio = new String[8];
            umRelatorio[0] = String.valueOf(relatorio.getId());
            umRelatorio[1] = String.valueOf(relatorio.getMotorista().getId());
            umRelatorio[2] = String.valueOf(relatorio.getCarro().getId());
            umRelatorio[3] = String.valueOf(relatorio.getDataDoServico()); //LocalDate.parse(relatorio.getDataDoServico().toString(), formato).toString();
            umRelatorio[4] = String.valueOf(relatorio.getDataDoEnvio());//LocalDate.parse(relatorio.getDataDoEnvio().toString(), formato).toString();
            umRelatorio[5] = String.valueOf(relatorio.getKm_percorrido());
            umRelatorio[6] = String.valueOf(relatorio.isAvariaNoServico());
            umRelatorio[7] = String.valueOf(relatorio.getRelato());
            dadosRelatorios[posicao++] = umRelatorio;
        }
        DefaultTableModel modeloRel = new DefaultTableModel(
                dadosRelatorios, cposFigurinha);
        jtRelatorios.setModel(modeloRel);
    }
    
    private void popularCombos() {
        cMotorista.removeAllItems();
        List <Motorista> motoristas = MotoristaDAO.selecionarTodos();
        for (Motorista motorista : motoristas) {
            cMotorista.addItem(motorista.getNome());
        }
         cCarro.removeAllItems();
        List<Carro> carros = CarroDAO.selecionarTodos();
        for (Carro carro : carros) {
            cCarro.addItem(carro.getPlaca());
        }
    }
    
    private void selecionaMotorista(){
        tNome.setText(cMotorista.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpNovo = new javax.swing.JPanel();
        jMotorista = new javax.swing.JLabel();
        jCarro = new javax.swing.JLabel();
        jRelato = new javax.swing.JLabel();
        jNovoRelatorio = new javax.swing.JLabel();
        cMotorista = new javax.swing.JComboBox<>();
        cCarro = new javax.swing.JComboBox<>();
        jNome = new javax.swing.JLabel();
        jMatricula = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jPlaca = new javax.swing.JLabel();
        tPlaca = new javax.swing.JTextField();
        jMarca = new javax.swing.JLabel();
        tMarca = new javax.swing.JTextField();
        jModelo = new javax.swing.JLabel();
        tModelo = new javax.swing.JTextField();
        jKmAtual = new javax.swing.JLabel();
        tKmAnterior = new javax.swing.JTextField();
        cbAvarias = new javax.swing.JCheckBox();
        jDataServico = new javax.swing.JLabel();
        jDataEnvio = new javax.swing.JLabel();
        jKmPercorrido = new javax.swing.JLabel();
        tKmPercorrido = new javax.swing.JTextField();
        tRelato = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tMatricula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tDataServico = new javax.swing.JFormattedTextField();
        tDataEnvio = new javax.swing.JFormattedTextField();
        jAvariado = new javax.swing.JLabel();
        tAvariado = new javax.swing.JTextField();
        jpEditar = new javax.swing.JPanel();
        jpPesquisar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRelatorios = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMotorista.setText("Motorista");

        jCarro.setText("Carro");

        jRelato.setText("Relato");

        jNovoRelatorio.setText("Novo Relatório");

        cMotorista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cMotoristaItemStateChanged(evt);
            }
        });

        cCarro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cCarroItemStateChanged(evt);
            }
        });
        cCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCarroActionPerformed(evt);
            }
        });

        jNome.setText("Nome ");

        jMatricula.setText("Matricula");

        tNome.setEditable(false);
        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });

        jPlaca.setText("Placa");

        tPlaca.setEditable(false);
        tPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPlacaActionPerformed(evt);
            }
        });

        jMarca.setText("Marca");

        tMarca.setEditable(false);

        jModelo.setText("Modelo");

        tModelo.setEditable(false);

        jKmAtual.setText("Km Inicial");

        tKmAnterior.setEditable(false);

        cbAvarias.setText("Nova(s) avaria(s)");

        jDataServico.setText("Data do Servico");

        jDataEnvio.setText("Data do Envio");

        jKmPercorrido.setText("Km Final");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        tRelato.setViewportView(jTextArea1);

        tMatricula.setEditable(false);

        jButton1.setText("Cancelar");

        jButton2.setText("Salvar");

        tDataServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        tDataEnvio.setEditable(false);
        tDataEnvio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jAvariado.setText("Situação");

        tAvariado.setEditable(false);

        javax.swing.GroupLayout jpNovoLayout = new javax.swing.GroupLayout(jpNovo);
        jpNovo.setLayout(jpNovoLayout);
        jpNovoLayout.setHorizontalGroup(
            jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNovoLayout.createSequentialGroup()
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCarro)
                            .addComponent(cCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPlaca)
                            .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMarca)
                            .addComponent(tMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jModelo)
                            .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 332, Short.MAX_VALUE))
                    .addComponent(tRelato)
                    .addGroup(jpNovoLayout.createSequentialGroup()
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMotorista))
                                .addGap(18, 18, 18)
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNome))
                                .addGap(18, 18, 18)
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMatricula)
                                    .addComponent(tMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDataServico)
                                    .addComponent(tDataServico, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jAvariado)
                                    .addComponent(tAvariado))
                                .addGap(18, 18, 18)
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDataEnvio)
                                    .addComponent(tDataEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jNovoRelatorio)
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jKmAtual)
                                    .addComponent(tKmAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jKmPercorrido)
                                    .addComponent(tKmPercorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cbAvarias))
                            .addComponent(jRelato))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jpNovoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
        );
        jpNovoLayout.setVerticalGroup(
            jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNovoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jNovoRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpNovoLayout.createSequentialGroup()
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jMotorista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tDataServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDataEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jMatricula)
                                    .addComponent(jDataServico)
                                    .addComponent(jDataEnvio))
                                .addGap(28, 28, 28)))
                        .addGap(18, 18, 18)
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jCarro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpNovoLayout.createSequentialGroup()
                                .addComponent(jPlaca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpNovoLayout.createSequentialGroup()
                        .addComponent(jAvariado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAvariado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNovoLayout.createSequentialGroup()
                        .addComponent(jKmAtual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tKmAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpNovoLayout.createSequentialGroup()
                        .addComponent(jKmPercorrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tKmPercorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAvarias))))
                .addGap(18, 18, 18)
                .addComponent(jRelato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRelato, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jpNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo ", jpNovo);

        javax.swing.GroupLayout jpEditarLayout = new javax.swing.GroupLayout(jpEditar);
        jpEditar.setLayout(jpEditarLayout);
        jpEditarLayout.setHorizontalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        jpEditarLayout.setVerticalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editar", jpEditar);

        jtRelatorios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtRelatorios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(jtRelatorios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPesquisarLayout = new javax.swing.GroupLayout(jpPesquisar);
        jpPesquisar.setLayout(jpPesquisarLayout);
        jpPesquisarLayout.setHorizontalGroup(
            jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 794, Short.MAX_VALUE)
        );
        jpPesquisarLayout.setVerticalGroup(
            jpPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPesquisarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pesquisar", jpPesquisar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCarroActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void tPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPlacaActionPerformed

    private void cMotoristaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cMotoristaItemStateChanged
        Motorista motorista = MotoristaDAO.selecionarMotoristaPorNome(cMotorista.getSelectedItem().toString());
        tNome.setText(motorista.getNome());
        tMatricula.setText(motorista.getMatricula());
        tDataEnvio.setText(LocalDate.now().format(formato));
        tDataServico.setText(LocalDate.now().format(formato));
    }//GEN-LAST:event_cMotoristaItemStateChanged

    private void cCarroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cCarroItemStateChanged
        Carro carro = CarroDAO.selecionarCarroPorPlaca(cCarro.getSelectedItem().toString());
        tPlaca.setText(carro.getPlaca());
        tMarca.setText(carro.getMarca());
        tModelo.setText(carro.getModelo());
        tKmAnterior.setText(String.valueOf(carro.getKm_atual()));
        if(carro.getAvariado() > 0){
            tAvariado.setText("Levar a Oficina");
        } else {
            tAvariado.setText("Pronto ");
        }
    }//GEN-LAST:event_cCarroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RelatorioGUI().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(RelatorioGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cCarro;
    private javax.swing.JComboBox<String> cMotorista;
    private javax.swing.JCheckBox cbAvarias;
    private javax.swing.JLabel jAvariado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jCarro;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jDataEnvio;
    private javax.swing.JLabel jDataServico;
    private javax.swing.JLabel jKmAtual;
    private javax.swing.JLabel jKmPercorrido;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jMatricula;
    private javax.swing.JLabel jModelo;
    private javax.swing.JLabel jMotorista;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNovoRelatorio;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jPlaca;
    private javax.swing.JLabel jRelato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpEditar;
    private javax.swing.JPanel jpNovo;
    private javax.swing.JPanel jpPesquisar;
    private javax.swing.JTable jtRelatorios;
    private javax.swing.JTextField tAvariado;
    private javax.swing.JFormattedTextField tDataEnvio;
    private javax.swing.JFormattedTextField tDataServico;
    private javax.swing.JTextField tKmAnterior;
    private javax.swing.JTextField tKmPercorrido;
    private javax.swing.JTextField tMarca;
    private javax.swing.JTextField tMatricula;
    private javax.swing.JTextField tModelo;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tPlaca;
    private javax.swing.JScrollPane tRelato;
    // End of variables declaration//GEN-END:variables
}
