/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.natanaelqn.relatorio.gui.motoristas;


import br.com.natanaelqn.relatorio.dao.CarroDAO;
import br.com.natanaelqn.relatorio.entity.Carro;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author natan
 */
public class AlterarMotorista extends javax.swing.JFrame {

    /**
     * Creates new form AdicionarVeiculo
     */
    public AlterarMotorista() {
        initComponents();
        popularCombos();
    }
    
    private void popularCombos() {
        cCarro.removeAllItems();
        List<Carro> carros = CarroDAO.selecionarTodos();
        for (Carro carro : carros) {
            cCarro.addItem(carro.getPlaca());
        }
        List<String> avariado = new LinkedList<>();
        avariado.add("Não");
        avariado.add("Sim");
        atualiza();
    }
    
    private void atualiza(){
        Carro carro = CarroDAO.selecionarCarroPorPlaca(cCarro.getSelectedItem().toString());
        tPlacaAlterar.setText(carro.getPlaca());
        tMarcaAlterar.setText(carro.getMarca());
        tModeloAlterar.setText(carro.getModelo());
        tKmAtualAlterar.setText(String.valueOf(carro.getKm_atual()));
        cAvariadoAlterar.setSelectedItem(carro.getAvariado());
        if (carro.getAvariado().equalsIgnoreCase("Sim")) {
            tAvariaAlterar.setText("Levar a Oficina");
        } else {
            tAvariaAlterar.setText("Pronto");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpInserirVeiculo = new javax.swing.JPanel();
        jCarro = new javax.swing.JLabel();
        jMarca = new javax.swing.JLabel();
        tMarcaAlterar = new javax.swing.JTextField();
        tModeloAlterar = new javax.swing.JTextField();
        jModelo = new javax.swing.JLabel();
        jAvariado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jAlterar = new javax.swing.JButton();
        jCancelarAlterar = new javax.swing.JButton();
        tKmAtualAlterar = new javax.swing.JTextField();
        jKmAtual = new javax.swing.JLabel();
        tPlacaAlterar = new javax.swing.JTextField();
        cAvariadoAlterar = new javax.swing.JComboBox<>();
        lAvaria = new javax.swing.JLabel();
        tAvariaAlterar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cCarro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jCarro.setText("Placa");

        jMarca.setText("Marca");

        jModelo.setText("Modelo");

        jAvariado.setText("Avariado");

        jLabel1.setText("Alterar Veiculo");

        jAlterar.setText("Alterar");
        jAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarActionPerformed(evt);
            }
        });

        jCancelarAlterar.setText("Cancelar");
        jCancelarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarAlterarActionPerformed(evt);
            }
        });

        jKmAtual.setText("Km Atual");

        cAvariadoAlterar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        lAvaria.setText("Situação");

        jLabel2.setText("Veiculo");

        cCarro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cCarroItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jpInserirVeiculoLayout = new javax.swing.GroupLayout(jpInserirVeiculo);
        jpInserirVeiculo.setLayout(jpInserirVeiculoLayout);
        jpInserirVeiculoLayout.setHorizontalGroup(
            jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCancelarAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jKmAtual)
                                    .addComponent(tKmAtualAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAvariado)
                                    .addComponent(cAvariadoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lAvaria)
                                    .addComponent(tAvariaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMarca)
                                    .addComponent(tMarcaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tModeloAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jModelo)
                                    .addComponent(jCarro)
                                    .addComponent(tPlacaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jpInserirVeiculoLayout.setVerticalGroup(
            jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInserirVeiculoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tPlacaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCarro)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addComponent(jModelo)
                        .addGap(6, 6, 6)
                        .addComponent(tModeloAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addComponent(jMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tMarcaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                            .addComponent(jKmAtual)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tKmAtualAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInserirVeiculoLayout.createSequentialGroup()
                            .addComponent(jAvariado)
                            .addGap(6, 6, 6)
                            .addComponent(cAvariadoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpInserirVeiculoLayout.createSequentialGroup()
                        .addComponent(lAvaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tAvariaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jpInserirVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAlterar)
                    .addComponent(jCancelarAlterar))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Alterar Veiculo", jpInserirVeiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarAlterarActionPerformed
        atualiza();
        dispose();
    }//GEN-LAST:event_jCancelarAlterarActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        /*try {
            atualizaRelatoriosEnviados();
            atualizaRelatoriosRecebidos();
        } catch (ParseException ex) {
            Logger.getLogger(DiretorGUI.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarActionPerformed
        Carro carro = CarroDAO.selecionarCarroPorPlaca(cCarro.getSelectedItem().toString());
        carro.setPlaca(tPlacaAlterar.getText());
        carro.setMarca(tMarcaAlterar.getText());
        carro.setModelo(tModeloAlterar.getText());
        carro.setKm_atual(Integer.parseInt(tKmAtualAlterar.getText()));
        carro.setAvariado(cAvariadoAlterar.getSelectedItem().toString());
        carro.setAvaria(tAvariaAlterar.getText());
        CarroDAO.alterar(carro);     
        atualiza();
    }//GEN-LAST:event_jAlterarActionPerformed

    private void cCarroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cCarroItemStateChanged
        atualiza();
    }//GEN-LAST:event_cCarroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cAvariadoAlterar;
    private javax.swing.JComboBox<String> cCarro;
    private javax.swing.JButton jAlterar;
    private javax.swing.JLabel jAvariado;
    private javax.swing.JButton jCancelarAlterar;
    private javax.swing.JLabel jCarro;
    private javax.swing.JLabel jKmAtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jModelo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpInserirVeiculo;
    private javax.swing.JLabel lAvaria;
    private javax.swing.JTextField tAvariaAlterar;
    private javax.swing.JTextField tKmAtualAlterar;
    private javax.swing.JTextField tMarcaAlterar;
    private javax.swing.JTextField tModeloAlterar;
    private javax.swing.JTextField tPlacaAlterar;
    // End of variables declaration//GEN-END:variables
}
